OAuthConsumerKey: "PUTKEYHERE"
AuthConsumerSecret: "PUTKEYHERE"
OAuthAccessToken: "PUTKEYHEREE"
OAuthAccessTokenSecret: "PUTKEYHERE"
kafkaBrokerList: "mhassani-ndebian:9092"
kafkaToic: "test-45"
searchQuery: "Text"
mockFilePath: "./config/mockData.txt"